### ISSUE TITLE
How to add branch with collapsed leafs

### ISSUE THREAD

**Issue by sree07** [ludo/jquery-treetable#119]
Hi ludo, i have a requirement of adding a branch with leafs, with all leafs as collapsed. I have tested loadBranch function but it always add branch as collapsed but leafs always as expanded. can you help me to find a way to add leafs as collapsed.

Thanks
sree

**Comment by jeffvannijlen** [comment]
@Ludo, is this the way to go (collapse & reveal) or is there a better way?
