### ISSUE TITLE
how to refresh data?

### ISSUE THREAD

**Issue by sapien99** [ludo/jquery-treetable#128]
Hi guys,

i like treetable a lot, but i ran into a little issue: i need to refresh the treetable periodically, showing a status-view of some nested services. 
The initial setup of the tree works fine, the table is expandable and shows the list of services in a nested structure. 
The problem starts when refreshing the tree periodically looping over the services and recreating the innerHTML of the <tr> to change the status of the service. createServiceRow just creates a string containing the td-elements. 

`_.forEach(service,function(service) {
  $('#'+service.id).html(createServiceRow(service));
})`

This results in completely loosing the table structure. What seems to be weird for me: the data-tt-id and data-tt-parent-id are still on the tr, but still everything is renderes as a plain table without nesting.

doing a `$('#'+tableId).treetable({expandable:true},true); `

and forcing the table recreation works, but constantly collapses/expands the table.

Is the only option to force the recreation and store info about the expanded nodes to expand them after the recreation or is there a simple method to refresh table data and reflect it on the treetable?

Taking a look at how treetable renders a nested row i guess i have an explanation why this happens:

`<tr id="s2" data-tt-id="s1" data-tt-parent-id="s1" class="collapsed leaf" style="display: table-row;"><td><span class="indenter" style="padding-left: 19px;"></span>nok</td><td>unknown</td></tr>`

changing the innerhtml of the tr i also loose the <span> which is created by treetable to render a nested row - but how can i prevent this? i tried to rerender the node after the refresh using treetable("node",id).render(), but that does not change anything :-( What am i doing wrong?

Thanks a lot and Cheers
Michi

**Comment by achapman77** [comment]
If trying to refresh the whole table, it appears <table> holds on to instance of tabletree.  Destroy <table> and rebuild.
