### ISSUE TITLE
JQuery TreeTable not working in IE (8, 9, 10, 11)

### ISSUE THREAD

**Issue by gova515** [ludo/jquery-treetable#140]
Hello,

I have installed jquery treetable plugin in to my project, It is working excellent in Chrome, Firefox, but when it comes to IE it is just displaying the data as normal rows rather than showing in Tree View. I have installed this Jquery file in my project which is using MVC C#. 
Do we have any fix for this? Please do help me.

I also do some changes in jquery.treetable.js specified in #66, but it doesn't help. It is still showing like a normal table rather than a tree table. Any other suggestions?

Thanks in advance.

**Comment by akeepanchal31** [comment]
@ludo @gova515 @jens @davereid @Petah Hello All here is a simple solution i found for jQuery treetable IE issue you can use TreeGrid Bootstrap 3 it's an cool substitution for this and supports all the browser here is an example link http://maxazan.github.io/jquery-treegrid/examples/example-bootstrap-3.html
