### ISSUE TITLE
Collapse/Expand functionality not working

### ISSUE THREAD

**Issue by kingtrocko** [ludo/jquery-treetable#161]
In my table the expand image is not being rendered and thus the Expand and collapse functionality is not working. All the Tree is displayed expanded as shown in the image.

`<a href="#" title="Collapse">&nbsp;</a>`

This anchor tag is not added in my html table.

any idea why? or how can I solve this issue?

![capture](https://cloud.githubusercontent.com/assets/2686234/5982173/32495862-a886-11e4-8476-59921668c8c1.JPG)

**Comment by jbwl** [comment]
I have the same problem.
