### ISSUE TITLE
does not work when order of tr is not correct even data-tt-id, data-tt-parent-id is corrct

### ISSUE THREAD

**Issue by mehebubhossain** [ludo/jquery-treetable#172]
Here is example
```
<tr data-tt-id="0" data-tt-parent-id="">
<td>0</td>  
</tr>
<tr data-tt-id="1" data-tt-parent-id="0">
<td>1</td>  
</tr>
<tr data-tt-id="2" data-tt-parent-id="0">
<td>2</td>  
</tr>
<tr data-tt-id="3" data-tt-parent-id="1">
<td>3</td>  
</tr>
```
The last tr with data-tt-id="3"  should be under tr with data-tt-id="1" because it's data-tt-parent-id="1" but it showing under data-tt-id="2"
![image](https://cloud.githubusercontent.com/assets/4637381/8431870/ee30d074-1f59-11e5-931c-83054c1ab63e.png)

Please let me know it this could be fixed

**Comment by acacha** [comment]
It's explicitly warned in the docs the importance of order. You could use at backend something like https://github.com/etrepat/baum to assure order using lft column

**Comment by ludo** [comment]
^ what @acacha said :)
