### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mohitmunjal2801** [ludo/jquery-treetable#176]
Taking too much time to render more than 5000 nodes/rows and sometimes corrupt the webpage also.

**Comment by SchweizerSchoggi** [comment]
Did you already try this fix?
https://github.com/ludo/jquery-treetable/issues/144

**Comment by mohitmunjal2801** [comment]
I have got more than 50000 rows but i have solved the issue using setInterval.In which i am loading the rows in parts.Suppose i have 1000 rows then i am loading the rows in the bundle of 100s.

**Comment by ludo** [comment]
Marking as duplicate of #144.
