### ISSUE TITLE
Tree nodes sometimes does not expand

### ISSUE THREAD

**Issue by flodi** [ludo/jquery-treetable#197]
Here http://farmabios.e-scientia.eu/magazzino/attivita-cdc/ (use test test to access) clicking on the arrows expand only some nodes, but I do not see any error in console, and trecking on inspector seems all correct.

**Comment by juniobill** [comment]
The data-tt-id attribute is duplicate, it must be unique across the table

**Comment by flodi** [comment]
Dho, so the bug was in my head.

------------------------------
Fabrizio Lodi
President
Mobile 335345390
Fax 0292853287
Mail flodi@e-scientia.eu
Follow me @_flodi
http://it.linkedin.com/in/flodi

From: junio <notifications@github.com> <notifications@github.com>
Reply: ludo/jquery-treetable
<reply@reply.github.com>
<reply@reply.github.com>
Date: 16 March 2017 at 15:06:33
To: ludo/jquery-treetable <jquery-treetable@noreply.github.com>
<jquery-treetable@noreply.github.com>
Cc: Fabrizio Lodi <flodi@e-scientia.eu> <flodi@e-scientia.eu>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [ludo/jquery-treetable] Tree nodes sometimes does not expand
(#197)

The data-tt-id attribute is duplicate, it must be unique across the table

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ludo/jquery-treetable/issues/197#issuecomment-287067103>,
or mute the thread
