### ISSUE TITLE
treetable 3.0.1 won't work using the java framework Wicket (in development mode)

### ISSUE THREAD

**Issue by tbl0605** [ludo/jquery-treetable#66]
Hello,
I'm using treetable 3.0.1 (and jquery 1.8.3) in combinaison with the java web application framework Wicket 1.5
This framework can be started in 2 modes : development and deployment mode.
In development mode, the resulting html pages contains a lot of "wicket:" tags and tag attributes (that don't show up in deployment mode).
Sadly, the treetable plugin doesn't work correctly using internet explorer 8 and Wicket in development mode.

I've attached a zip file containing 2 web pages saved using internet explorer 8 (with anonymised data). The "deployment mode.htm" page will work correctly using internet explorer 8, but the "development mode.htm" won't work.
No problem so far using Chrome and Firefox.

Hope my english is not too bad :)

Thierry.

PS : Change the attached file extension from ".jpg" to ".zip" 

![demo](https://f.cloud.github.com/assets/3315731/429955/b7e46fbe-ae57-11e2-90f2-0c10bd93a3f9.jpg)

**Comment by akeepanchal31** [comment]
@ludo @gova515 @jens @davereid @Petah Hello All here is a simple solution i found for jQuery treetable IE issue you can use TreeGrid Bootstrap 3 it's an cool substitution for this and supports all the browser here is an example link http://maxazan.github.io/jquery-treegrid/examples/example-bootstrap-3.html
