### ISSUE TITLE
Is it possible to have a vertical scrollbar on the tree table?

### ISSUE THREAD

**Issue by dlwhiteman** [ludo/jquery-treetable#84]
I have the possibility of needing to support a lot of data in the tree table.  Is it possible to get a scrollbar to appear dynamically if the tree content exceeds the bounds of the widget?  I tried the following style with no luck:

```
.treetable {
overflow: scroll;
}
```

Thanks,
David

**Comment by rahulvar** [comment]
I recently started using tree table and came across same problem. I was able to fix this by enabling horizontal scrolling using style sheet inside <div> tag with "white-space: nowrap" as follows:

```
<div style='height:100%; max-height:520px;width:427px;border:1px #808080 solid;vertical-align:top;display:inline-block;overflow: hidden;'>
    <div id="ttSize" style='max-height:520px;height:520px;overflow-y: scroll; overflow-x: scroll; white-space:nowrap;'> 
        <table id=nh_table style='border:none;'>
            <tbody>
            <tr data-tt-branch='true' data-tt-id='bcp_farm'><td><span class=bcp_farm>Boardwalk Farm</span></td></tr>
            </tbody>  
        </table>
    </div>
</div>
```
The image below shows how horizontal scroll bar is visible when it exceeds the width of tree table.

![image](https://user-images.githubusercontent.com/21053848/29465169-eea5db68-8455-11e7-9cfe-031698d9fe72.png)
