### ISSUE TITLE
TR parent ID does no update when Node moved

### ISSUE THREAD

**Issue by digitalsoul1973** [ludo/jquery-treetable#88]
When calling the Move function, should the parent ID attribute on the TR not be updated to reflect the new parentID on the node? Currently I'm changing this explicitly whenever I move a node, but cant think of any reason why this shouldn't happen as part of the setParent method. Is this an oversight or is there a reason for this? I'd even settle for having to reinitialize the node to update the parent ID over what I'm having to do currently.

**Comment by romannovotny** [comment]
> The parent id data attribute is updated in memory, but this is not reflected in the HTML as per jQuery's implementation of the data functions (see https://github.com/ludo/jquery-treetable/blob/master/javascripts/src/jquery.treetable.js#L158). Updating the TR in the DOM is expensive so I try to avoid it when it is not necessary. If you want to you can update the DOM in the `changeData` event, fired when the data cache is updated.
> 
> Also see this related StackOverflow question: http://stackoverflow.com/questions/5507718/why-dont-changes-to-jquery-fn-data-update-the-corresponding-html-5-data-a

Could you tell me how to obtain parentId from data cache? Not skilled in jquery so I am little lost or show example hot to use changeData?
