### ISSUE TITLE
Safari browser works really slow

### ISSUE THREAD

**Issue by gam6itko** [ludo/jquery-treetable#94]
I have table with about 1000 table rows. When I call method 
$("#example-advanced").treetable({expandable: true});
on Chrome Browser it works very fast, about 3 seconds.

But on Safari browser it works more slowly.

Finally, on IPad2 Safari Browser it works VERY VERY SLOW. About 1 minute.

Can you improve performance for Safari Browsers ?

**Comment by MacMaru** [comment]
@ludo we notice a huge discrepancy in safari compared to chrome/firefox as well: you closed this issue, any solution?
